function transmitSpeedAP = ComputeTransmitSpeedAP(...
    rho, ...
    divisionPercentageEquivalentAP, ...
    totalComputeResourceAP,...
    betaSum...
    )


transmitSpeedAP = totalComputeResourceAP...
    .* (1 + (rho - 1) * divisionPercentageEquivalentAP + betaSum)...
    ./ divisionPercentageEquivalentAP;

end