function alpha = GetAlphaAP(...
    nAP,...
    compressionRatio,...
    totalTransmitResourceCC,...
    generateSpeedEquivalentAP,...
    totalComputeResourceAP,...
    childStartIdx,...
    nChilds,...
    generateSpeedAP,...
    transmitSpeedED,...
    generateSpeedED,...
    computeCapacityED)

fun = @(x)OptimizeFunctionAP(...
    x,...
    nAP,...
    compressionRatio,...
    totalTransmitResourceCC,...
    generateSpeedEquivalentAP,...
    totalComputeResourceAP,...
    childStartIdx,...
    nChilds,...
    generateSpeedAP,...
    transmitSpeedED,...
    generateSpeedED,...
    computeCapacityED);

x0 = rand();
[alpha, fval] = fsolve(fun, x0);

end