function f = OptimizeFunctionAP(...
    alpha,...
    nAP,...
    compressionRatio,...
    totalTransmitResourceCC,...
    generateSpeedEquivalentAP,...
    totalComputeResourceAP,...
    childStartIdx,...
    nChilds,...
    generateSpeedAP,...
    transmitSpeedED,...
    generateSpeedED,...
    computeCapacityED)

divisionPercentageED = ComputeDivisionPercentageED(alpha, computeCapacityED, generateSpeedED);
[generateSpeedEquivalentAP,...
    ~,...
    betaSum,...
    generateSpeedAP,...
    ~,...
    ~,...
    ~]...
    = InitApLayerParams(...
    nAP,...
    compressionRatio,...
    totalComputeResourceAP,...
    childStartIdx,...
    nChilds,...
    divisionPercentageED,... 
    transmitSpeedED ...
    );


kalpha = generateSpeedED(1) / computeCapacityED(1) * alpha;
divisionPercentageEquivalentAP = ...
    ComputeDivisionPercentageEquivalentAP(...
        kalpha, ...
        generateSpeedEquivalentAP, ...
        totalComputeResourceAP...
    );

transmitSpeedAP = ComputeTransmitSpeedAP(...
    compressionRatio, ...
    divisionPercentageEquivalentAP, ...
    totalComputeResourceAP,...
    betaSum...
    );

f = abs(sum(transmitSpeedAP) - totalTransmitResourceCC);

end