function L = LatencyFunction(...
    compressionRatio,...
    generateSpeedED, ...
    divisionPercentageED,...
    divisionPercentageAP,...
    divisionPercentageCC,...
    computeCapacityTotal,...
    transmitResourceWireless,...
    transmitResourceWired)
% Lm(s)
% Here division percentage is different
% s_ED + s_AP + s_CC = 1 here

term1 = sqrt(generateSpeedED .* divisionPercentageED) ...
    + sqrt(generateSpeedED .* divisionPercentageAP)...
    + sqrt(generateSpeed .* divisionPercentageCC);
term1 = sum(sum(term1))^2 / computeCapacityTotal;

term2 = generateSpeedED...
    .* (compressionRatio*divisionPercentageED + divisionPercentageAP + divisionPercentageCC);
term2 = sum(sum(sqrt(term2)))^2 / transmitResourceWireless;

term3 = generateSpeedED...
    .* (compressionRatio*(divisionPercentageED + divisionPercentageAP) + divisionPercentageCC);
term3 = sum(sum(sqrt(term3)))^2 / transmitResourceWired;

L = term1 + term2 + term3;

end

